name: CI Pipeline

on:
  push:
    branches:
      - '*'  # This makes the pipeline run on push to any branch
  pull_request:
    branches:
      - '*'  # This makes the pipeline run on pull requests to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build Docker Image
      run: docker-compose build

    - name: Run Docker Containers
      run: docker-compose up -d

    - name: List Docker Containers
      run: docker ps

    - name: Save Docker state
      run: docker-compose ps -q > container_ids.txt

    - name: Upload Docker state
      uses: actions/upload-artifact@v2
      with:
        name: container_ids
        path: container_ids.txt

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Download Docker state
      uses: actions/download-artifact@v2
      with:
        name: container_ids

    - name: Run Tests
      run: |
        container_id=$(cat container_ids.txt | head -n 1)
        echo "Container ID: $container_id"
        if [ -n "$container_id" ]; then
          docker exec $container_id pytest tests/
        else
          echo "Error: Container not found" >&2
          exit 1
        fi

    - name: Shut down Docker Containers
      run: docker-compose down
