name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build Docker Image
      run: docker-compose build

    - name: Run Docker Containers
      run: docker-compose up -d

    - name: Run Tests
      run: |
        container_name=$(docker ps --filter "name=trivia_game_web" --format "{{.Names}}")
        echo "Container Name: $container_name"
        if [ -n "$container_name" ]; then
          docker exec $container_name pytest tests/
        else
          echo "Error: Container not found" >&2
          exit 1
        fi



    - name: Shut down Docker Containers
      run: docker-compose down
